using Core.Domain;

namespace Core.Interfaces;

public interface ITradeExecutor
{
	/// <summary>
	/// Validates and executes a trading signal generated by a strategy.
	/// Places a real order on the exchange and returns the resulting trade record.
	/// Returns null if the signal is Hold or validation fails.
	/// </summary>
	/// <param name="solution">The trading signal to execute.</param>
	/// <param name="bot">The bot configuration containing exchange and symbol info.</param>
	/// <param name="ct">Cancellation token.</param>
	/// <returns>A <see cref="BotTradeRecord"/> if the order was placed, otherwise null.</returns>
	/// <exception cref="InvalidOperationException">Thrown if the exchange connection is not found or order placement fails.</exception>
	Task<BotTradeRecord?> ExecuteAsync(TradingSolution solution, BotConfiguration bot, CancellationToken ct = default);
}
