using Core.Domain;
using Core.Interfaces;

namespace Infrastructure.Trading;

/// <summary>
/// Validates and executes trading signals generated by a strategy against a real exchange.<br/>
/// Retrieves the exchange connection and portfolio for the bot's owner, verifies that sufficient
/// balance is available, and places a market order via the exchange service.<br/>
/// Returns null if the signal is Hold or if balance validation fails.
/// </summary>
public class TradeExecutor : ITradeExecutor
{
	private readonly IExchangeServiceFactory _exchangeServiceFactory;
	private readonly IUserService _userService;

	public TradeExecutor(IExchangeServiceFactory exchangeServiceFactory, IUserService userService)
	{
		_exchangeServiceFactory = exchangeServiceFactory;
		_userService = userService;
	}

	/// <summary>
	/// Validates and executes a trading signal generated by a strategy.<br/>
	/// Fetches the user's exchange connection and portfolio, verifies sufficient balance,
	/// and places a market order on the exchange.
	/// </summary>
	/// <param name="solution">The trading signal to execute.</param>
	/// <param name="bot">The bot configuration containing exchange, symbol, and risk parameters.</param>
	/// <param name="ct">Cancellation token.</param>
	/// <returns>
	/// A <see cref="BotTradeRecord"/> with execution details if the order was placed successfully,
	/// or null if the signal is <see cref="SolutionType.Hold"/> or balance validation fails.
	/// </returns>
	/// <exception cref="InvalidOperationException">
	/// Thrown if the trading pair is not found on the exchange.
	/// </exception>
	public async Task<BotTradeRecord?> ExecuteAsync(TradingSolution solution, BotConfiguration bot, CancellationToken ct = default)
	{
		if (solution.Type == SolutionType.Hold)
			return null;

		var connection = await _userService.GetExchangeConnection(bot.UserId, bot.Exchange);
		var exchangeService = _exchangeServiceFactory.Create(bot.Exchange);

		var pairInfo = await exchangeService.GetTradingPairInfo(bot.Symbol, connection, ct);
		if (pairInfo is null)
			throw new InvalidOperationException($"Trading pair '{bot.Symbol}' not found on {bot.Exchange}");

		var portfolio = await exchangeService.GetPortfolio(bot.UserId, connection, ct);
		var side = solution.Type == SolutionType.Buy ? OrderSide.Buy : OrderSide.Sell;

		if (!HasSufficientBalance(portfolio, solution, side, bot))
			return null;

		// TODO: Support configurable order types (Limit, StopLoss, etc.) via RiskParameters.OrderType
		var order = new Order
		{
			Id = Guid.NewGuid().ToString(),
			ExchangeOrderId = string.Empty,
			Exchange = bot.Exchange,
			Symbol = bot.Symbol,
			Side = side,
			Type = OrderType.Market,
			Quantity = solution.Quantity,
			IsTestnet = connection.IsTestnet
		};

		var placedOrder = await exchangeService.PlaceOrder(order, connection, ct);

		return new BotTradeRecord
		{
			Id = Guid.NewGuid().ToString(),
			BotId = bot.Id,
			UserId = bot.UserId,
			Symbol = bot.Symbol,
			Side = side,
			Price = placedOrder.AverageFillPrice ?? 0,
			Quantity = placedOrder.FilledQuantity,
			Reason = solution.Reason,
			ExecutedAt = placedOrder.ExecutedAt ?? DateTimeOffset.UtcNow
		};
	}

	private static bool HasSufficientBalance(Portfolio portfolio, TradingSolution solution, OrderSide side, BotConfiguration bot)
	{
		if (side == OrderSide.Buy)
		{
			var baselineBalance = portfolio.Balances
				.FirstOrDefault(b => b.Asset.Equals(bot.QuoteAsset, StringComparison.OrdinalIgnoreCase));
			return baselineBalance?.Free >= bot.RiskParameters.PositionSize;
		}
		else
		{
			var assetBalance = portfolio.Balances
				.FirstOrDefault(b => b.Asset.Equals(bot.BaseAsset, StringComparison.OrdinalIgnoreCase));
			return assetBalance?.Free >= solution.Quantity;
		}
	}
}
